### ISSUE TITLE
Exponea cant detect projectToken when using .plist init

### ISSUE THREAD

**Issue by jackjpark** [exponea/exponea-ios-sdk#3] opened 2019-02-19 12:39 UTC
Hi, I am initialising exponea with the below configuration

```
<dict>
	<key>authorization</key>
	<string>Token redacted token</string>
	<key>automaticPushNotificationTracking</key>
	<true/>
	<key>sessionTimeout</key>
	<integer>20</integer>
	<key>projectToken</key>
	<string>redacted project id</string>
	<key>projectMapping</key>
	<dict/>
	<key>lastSessionStarted</key>
	<integer>0</integer>
	<key>lastSessionEnded</key>
	<integer>0</integer>
	<key>autoSessionTracking</key>
	<false/>
	<key>baseURL</key>
	<string>https://api.exponea.com</string>
</dict>
```

I call: ` Exponea.shared.configure(plistName: configPath)` with the above file

Then when I call `Exponea.shared.identifyCustomer`

I get a fatal crash on:

`var request = URLRequest(url: URL(string: path)!)` in the request factory

aswell as a print of 'ExponeaSDK ❗️ ERROR [Configuration.swift]:164 tokens(for:): No project token found.'

It would appear Exponea isnt reading the projectID from the config correctly? but it appears to be included in the request URL `path` just fine, so not sure if this is a bug?

Thanks

**Comment by nickskull** [comment] 2019-02-19 13:25
Hi Jack,

can you please try removing the empty dictionary for projectMapping from your plist file?

```
<key>projectMapping</key> <dict/>
```

**Comment by jackjpark** [comment] 2019-02-19 14:25
> Hi @jackjpark,
> 
> can you please try removing the empty dictionary for projectMapping from your plist file?
> 
> ```
> <key>projectMapping</key> <dict/>
> ```

Thanks, tried this but it hasnt resolved the crash on that URL force unwrap line, the Exponea error line seems to have disappeared from the debugger though if thats of use.

Interestingly, the code will execute beyond the force upwrap if i breakpoint, but when it crashes it always shows that line as the error

**Comment by nickskull** [comment] 2019-02-19 14:26
@jackjpark thanks for a quick answer. Could you please tell me what device and iOS version are using?

**Comment by jackjpark** [comment] 2019-02-19 14:27
> @jackjpark thanks for a quick answer. Could you please tell me what device and iOS version are using?

This is on the xcode simulator, any device. iOS 12

**Comment by nickskull** [comment] 2019-02-19 14:27
@jackjpark Actually, now looking the config one more time - can you try changing the baseURL key to `baseUrl` instead?

```
        <key>baseUrl</key>
	<string>https://api.exponea.com</string>
```

**Comment by jackjpark** [comment] 2019-02-19 14:32
> @jackjpark Actually, now looking the config one more time - can you try changing the baseURL key to `baseUrl` instead?
> 
> ```
>         <key>baseUrl</key>
> 	<string>https://api.exponea.com</string>
> ```

no luck im afraid, same result as above

**Comment by nickskull** [comment] 2019-02-19 14:37
@jackjpark Hmm, strange, I was convinced this would do the trick. Ok, let me investigate a bit more.

**Comment by jackjpark** [comment] 2019-02-19 14:38
> @jackjpark Hmm, strange, I was convinced this would do the trick. Ok, let me investigate a bit more.

No problem, i believed i had it working when i used the Configuration object, but wanted the .plist method for simpler management and then ran into this issue

**Comment by jackjpark** [comment] 2019-02-22 13:35
@nickskull Hi where there any further findings on this yet? as its holding up our integration, cheers

**Comment by nickskull** [comment] 2019-02-22 13:41
@jackjpark Hi, I apologise, this has been deprioritized as we thought you were able to use the code based integration. We will look into this today.

**Comment by jackjpark** [comment] 2019-02-22 13:43
@nickskull no worries, we need to log our users into the customer feature, and we cant do so due to this issue (as we cant initialise the SDK)

**Comment by nickskull** [comment] 2019-02-22 13:45
@jackjpark Are you getting the same issue when initialising using code? Ie. by calling:

```
Exponea.shared.configure(projectToken: token, authorization: auth, baseUrl: baseUrl)
```

**Comment by jackjpark** [comment] 2019-02-22 13:52
> @jackjpark Are you getting the same issue when initialising using code? Ie. by calling:
> 
> ```
> Exponea.shared.configure(projectToken: token, authorization: auth, baseUrl: baseUrl)
> ```

Its held as a lazy var and inits when the identifyUser method is called, will it need separate initialisation before hand?

**Comment by nickskull** [comment] 2019-02-22 13:55
You should ideally initialize before hand, but it shouldn't be necessary. The reason why it crashes is definitely because it either can't parse the base url properly or somehow the URL is getting malformed.  I'm looking into it now.

**Comment by nickskull** [comment] 2019-02-22 14:05
@jackjpark I have just tried with the exact same setup you have and it does not crash. Could you try and reproduce the error in a new project? I am wondering if you could have somehow altered the SDK behaviour by some extensions or swizzling?

**Comment by nickskull** [comment] 2019-02-22 14:12
Also, when the crash happens, could you try and `e print(path)` in the debugger or copy the value from the property inspector?

**Comment by jackjpark** [comment] 2019-02-22 14:37
> Also, when the crash happens, could you try and `e print(path)` in the debugger or copy the value from the property inspector?

I wont have time to create a new project any time soon, but the print out of the crash is 

`"https://api.exponea.com/track/v2/projects/<d47ab19e-2af0-11e9-81cd-0a58>/customers"` 

ive removed the last few digits as to not publicly leak out project ID!

**Comment by nickskull** [comment] 2019-02-22 14:51
Ok, so the issue here are the `<` and `>` signs around the project token. Are you sure that in your .plist file the token is written without these signs?

**Comment by jackjpark** [comment] 2019-02-22 15:00
> Ok, so the issue here are the `<` and `>` signs around the project token. Are you sure that in your .plist file the token is written without these signs?

yeah i thought that was a likely issue, but no, in the source code of the plist it reads as so

`<string>d47ab19e-2af0-11e9-81cd-0a580</string>`

**Comment by nickskull** [comment] 2019-02-22 15:28
@jackjpark Do you have any custom PropertyListDecoders or somehow alter the Codable behaviour in your application? Are there any extensions on Strings or similar that could alter the behaviour of the parsing in ExponeaSDK?

**Comment by jackjpark** [comment] 2019-02-22 15:31
> @jackjpark Do you have any custom PropertyListDecoders or somehow alter the Codable behaviour in your application? Are there any extensions on Strings or similar that could alter the behaviour of the parsing in ExponeaSDK?

we use sourcery to generate with AutoCodable, but this shouldnt touch the SDK or its plist in any way, there are no references to the plist or its properties anywhere else but when its parsed into Exponea.config

**Comment by nickskull** [comment] 2019-02-22 15:39
@jackjpark Could you upload the actual plist file you use without the tokens/auth for me?

**Comment by jackjpark** [comment] 2019-02-22 15:40
> @jackjpark Could you upload the actual plist file you use without the tokens/auth for me?

Is there a secure location to do this? i assume its not smart to post our full plists in public sight

**Comment by nickskull** [comment] 2019-02-22 15:42
That's why I wrote without the project ids/tokens :) But you can also email it to me at doha (at) nodesagency.com.

**Comment by jackjpark** [comment] 2019-02-22 15:43
sent you the file via email

**Comment by nickskull** [comment] 2019-02-22 16:25
@jackjpark I have just tested by using that exact file without any modifications and it worked flawlessly. I believe it must be some of your app's code interfering with the default `PropertyListDecoder` or `Codable` default implementation. Could you please double check that some of the tools or dependencies you're using are no interfering or overriding this. I'm afraid that the only solution I can recommend to you at this point is to configure Exponea from the code and not use a plist as that should work without any issues and shouldn't holdup your integration.

**Comment by jackjpark** [comment] 2019-02-22 16:29
> @jackjpark I have just tested by using that exact file without any modifications and it worked flawlessly. I believe it must be some of your app's code interfering with the default `PropertyListDecoder` or `Codable` default implementation. Could you please double check that some of the tools or dependencies you're using are no interfering or overriding this. I'm afraid that the only solution I can recommend to you at this point is to configure Exponea from the code and not use a plist as that should work without any issues and shouldn't holdup your integration.

i will investigate further and come back to you with the findings, thanks for your time

**Comment by jackjpark** [comment] 2019-02-25 10:13
Hi @nickskull I have revisited this today and decided to remove the plist from the equation and init the instance with the following, however the issue with the `<>` in the path when trying to identify users persist despite no longer using the plist, using the below results in the same issue:

` Exponea.shared.configure(projectToken: "d47ab19e-2af0-11e9-81cd-0a580a204889",
                                 authorization: .token("nnakfpujobb07fzre8kp6mlcuv0khsa77wwzr6d2229zltafjnn0s4r1ks72shct"))`

**Comment by nickskull** [comment] 2019-02-25 10:41
Hi @jackjpark, this is very interesting and strange at the same time. Could you please try downloading the SDK and running the example project and see if the same issue is happening there?

**Comment by jackjpark** [comment] 2019-02-25 12:15
> Hi @jackjpark, this is very interesting and strange at the same time. Could you please try downloading the SDK and running the example project and see if the same issue is happening there?

the example project runs and logs in fine, but it doesnt ever do the `identifyCustomer` function? im able to initialise the SDK, its when i call anything that i get the crash with the bad path

**Comment by jackjpark** [comment] 2019-02-25 13:07
@nickskull Ok, ive resolved the issue. So the SDK caches the .plist values, i noticed this when i deleted the projectID and it was still present in the path string. So it looks like it had cached an old version of my plist when i had the <> tags in it. Clearing the app from the devices and reinstalling from scratch picked up the new value and worked. Seems unnecessary to cache? as it caused quite a long issue to resolve here

**Comment by nickskull** [comment] 2019-02-25 14:22
@jackjpark That is the iOS caching the file, not the SDK (there is 0 code for caching plist files). :) It's common if you add a file and then remove it/change it that it doesn't reflect that, so almost always it's better to remove the app from the device and install again, somehow the copy files phase is broken sometimes. It is strange it was using the plist file when you switch to initialising using code though, could it be that you left the configure(plistName:) somewhere in the project after the code initialiser?

Anyway, glad that you resolved it and closing the issue.

**Closed by nickskull** 2019-02-25 14:22 UTC

**Comment by jackjpark** [comment] 2019-02-25 14:23
@nickskull ah fair enough, a good learning point regardless then. No i totally changed the initialiser so that is an odd behaviour, but all is working now regardless. thanks for your time and assistance
